import { useMemo } from "react";
import type { TokenState } from "../types/tokens";

export function usePreview(tokens: TokenState | null): React.CSSProperties {
  return useMemo(() => {
    if (!tokens) return {};
    return {
      "--brand-primary": tokens.brand.primary,
      "--brand-accent": tokens.brand.accent,
      "--brand-primary-light": tokens.brand.primaryLight,
      "--brand-accent-light": tokens.brand.accentLight,
      "--hot": tokens.pipeline.hot,
      "--qualified": tokens.pipeline.qualified,
      "--engaged": tokens.pipeline.engaged,
      "--warming": tokens.pipeline.warming,
      "--cold": tokens.pipeline.cold,
      "--hot-light": tokens.pipeline.hotLight,
      "--qualified-light": tokens.pipeline.qualifiedLight,
      "--engaged-light": tokens.pipeline.engagedLight,
      "--warming-light": tokens.pipeline.warmingLight,
      "--cold-light": tokens.pipeline.coldLight,
      "--success": tokens.status.success,
      "--success-light": tokens.status.successLight,
      "--warning": tokens.status.warning,
      "--warning-light": tokens.status.warningLight,
      "--error": tokens.status.error,
      "--error-light": tokens.status.errorLight,
      "--info": tokens.status.info,
      "--info-light": tokens.status.infoLight,
      "--neutral-50": tokens.neutral["50"],
      "--neutral-100": tokens.neutral["100"],
      "--neutral-200": tokens.neutral["200"],
      "--neutral-300": tokens.neutral["300"],
      "--neutral-400": tokens.neutral["400"],
      "--neutral-500": tokens.neutral["500"],
      "--neutral-600": tokens.neutral["600"],
      "--neutral-700": tokens.neutral["700"],
      "--neutral-800": tokens.neutral["800"],
      "--neutral-900": tokens.neutral["900"],
      "--background": tokens.neutral["50"],
      "--foreground": tokens.neutral["900"],
      "--card-background": "#FFFFFF",
      "--card-border": tokens.neutral["100"],
      "--muted": tokens.neutral["100"],
      "--muted-foreground": tokens.neutral["500"],
      "--space-1": `${tokens.spacing["1"]}px`,
      "--space-2": `${tokens.spacing["2"]}px`,
      "--space-3": `${tokens.spacing["3"]}px`,
      "--space-4": `${tokens.spacing["4"]}px`,
      "--space-5": `${tokens.spacing["5"]}px`,
      "--space-6": `${tokens.spacing["6"]}px`,
      "--space-8": `${tokens.spacing["8"]}px`,
      "--space-10": `${tokens.spacing["10"]}px`,
      "--space-12": `${tokens.spacing["12"]}px`,
      "--radius-xs": `${tokens.radius.xs}px`,
      "--radius-sm": `${tokens.radius.sm}px`,
      "--radius-md": `${tokens.radius.md}px`,
      "--radius-lg": `${tokens.radius.lg}px`,
      "--radius-xl": `${tokens.radius.xl}px`,
      "--radius-full": `${tokens.radius.full}px`,
      "--shadow-xs": tokens.shadow.xs,
      "--shadow-sm": tokens.shadow.sm,
      "--shadow-md": tokens.shadow.md,
      "--shadow-lg": tokens.shadow.lg,
      "--shadow-xl": tokens.shadow.xl,
      "--font-heading": `"${tokens.fontFamily.heading}", sans-serif`,
      "--font-body": `"${tokens.fontFamily.body}", sans-serif`,
      "--font-ui": `"${tokens.fontFamily.ui}", sans-serif`,
      "--font-stat": `"${tokens.fontFamily.stat}", sans-serif`,
      "--font-app-title": `"${tokens.fontFamily.appTitle}", sans-serif`,
      "--font-app-subtitle": `"${tokens.fontFamily.appSubtitle}", sans-serif`,
    } as React.CSSProperties;
  }, [tokens]);
}
